package net.irext.decoder.model;

public class RemoteIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.id
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.category_id
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.category_name
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.brand_id
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.brand_name
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.city_code
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.city_name
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.operator_id
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.operator_name
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.protocol
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.remote
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String remote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.remote_map
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String remoteMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.status
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.sub_cate
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Byte subCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.priority
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.remote_number
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String remoteNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.operator_name_tw
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String operatorNameTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.category_name_tw
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String categoryNameTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.brand_name_tw
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String brandNameTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.city_name_tw
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String cityNameTw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.binary_md5
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String binaryMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.contributor
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String contributor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_index.update_time
     *
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.id
     *
     * @return the value of remote_index.id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.id
     *
     * @param id the value for remote_index.id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.category_id
     *
     * @return the value of remote_index.category_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.category_id
     *
     * @param categoryId the value for remote_index.category_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.category_name
     *
     * @return the value of remote_index.category_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.category_name
     *
     * @param categoryName the value for remote_index.category_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.brand_id
     *
     * @return the value of remote_index.brand_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.brand_id
     *
     * @param brandId the value for remote_index.brand_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.brand_name
     *
     * @return the value of remote_index.brand_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.brand_name
     *
     * @param brandName the value for remote_index.brand_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.city_code
     *
     * @return the value of remote_index.city_code
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.city_code
     *
     * @param cityCode the value for remote_index.city_code
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.city_name
     *
     * @return the value of remote_index.city_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.city_name
     *
     * @param cityName the value for remote_index.city_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.operator_id
     *
     * @return the value of remote_index.operator_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.operator_id
     *
     * @param operatorId the value for remote_index.operator_id
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.operator_name
     *
     * @return the value of remote_index.operator_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.operator_name
     *
     * @param operatorName the value for remote_index.operator_name
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.protocol
     *
     * @return the value of remote_index.protocol
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.protocol
     *
     * @param protocol the value for remote_index.protocol
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.remote
     *
     * @return the value of remote_index.remote
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getRemote() {
        return remote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.remote
     *
     * @param remote the value for remote_index.remote
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setRemote(String remote) {
        this.remote = remote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.remote_map
     *
     * @return the value of remote_index.remote_map
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getRemoteMap() {
        return remoteMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.remote_map
     *
     * @param remoteMap the value for remote_index.remote_map
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setRemoteMap(String remoteMap) {
        this.remoteMap = remoteMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.status
     *
     * @return the value of remote_index.status
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.status
     *
     * @param status the value for remote_index.status
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.sub_cate
     *
     * @return the value of remote_index.sub_cate
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Byte getSubCate() {
        return subCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.sub_cate
     *
     * @param subCate the value for remote_index.sub_cate
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setSubCate(Byte subCate) {
        this.subCate = subCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.priority
     *
     * @return the value of remote_index.priority
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.priority
     *
     * @param priority the value for remote_index.priority
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.remote_number
     *
     * @return the value of remote_index.remote_number
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getRemoteNumber() {
        return remoteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.remote_number
     *
     * @param remoteNumber the value for remote_index.remote_number
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setRemoteNumber(String remoteNumber) {
        this.remoteNumber = remoteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.operator_name_tw
     *
     * @return the value of remote_index.operator_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getOperatorNameTw() {
        return operatorNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.operator_name_tw
     *
     * @param operatorNameTw the value for remote_index.operator_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setOperatorNameTw(String operatorNameTw) {
        this.operatorNameTw = operatorNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.category_name_tw
     *
     * @return the value of remote_index.category_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getCategoryNameTw() {
        return categoryNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.category_name_tw
     *
     * @param categoryNameTw the value for remote_index.category_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCategoryNameTw(String categoryNameTw) {
        this.categoryNameTw = categoryNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.brand_name_tw
     *
     * @return the value of remote_index.brand_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getBrandNameTw() {
        return brandNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.brand_name_tw
     *
     * @param brandNameTw the value for remote_index.brand_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setBrandNameTw(String brandNameTw) {
        this.brandNameTw = brandNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.city_name_tw
     *
     * @return the value of remote_index.city_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getCityNameTw() {
        return cityNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.city_name_tw
     *
     * @param cityNameTw the value for remote_index.city_name_tw
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setCityNameTw(String cityNameTw) {
        this.cityNameTw = cityNameTw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.binary_md5
     *
     * @return the value of remote_index.binary_md5
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getBinaryMd5() {
        return binaryMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.binary_md5
     *
     * @param binaryMd5 the value for remote_index.binary_md5
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setBinaryMd5(String binaryMd5) {
        this.binaryMd5 = binaryMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.contributor
     *
     * @return the value of remote_index.contributor
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getContributor() {
        return contributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.contributor
     *
     * @param contributor the value for remote_index.contributor
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setContributor(String contributor) {
        this.contributor = contributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_index.update_time
     *
     * @return the value of remote_index.update_time
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_index.update_time
     *
     * @param updateTime the value for remote_index.update_time
     * @mbggenerated Thu May 04 12:06:44 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}